# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0013_reserva'),
        ('ces', '0010_auto_20171013_2343'),
    ]

    operations = [
    ]
