# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0014_merge_20171014_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='movimentacao_id_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='movimentacao_id_origem',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='destinatario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='ces.Movimentacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='remetente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='ces.Movimentacao'),
            preserve_default=False,
        ),
    ]
